
#define nop(x) associate( x => x ); end associate

module artn_data

  !> @brief Module for storing the input/output data when pARTn is run through the API.
  !!
  !!


  use units, only: DP
  !! datatype encoders
  integer, parameter, public :: &
       ARTN_DTYPE_UNKNOWN = -1, &
       ARTN_DTYPE_INT     = 0, &
       ARTN_DTYPE_REAL    = 1, &
       ARTN_DTYPE_BOOL    = 2, &
       ARTN_DTYPE_STR     = 3
  !! err codes
  integer, parameter, public :: &
       ARTN_ERR_EIGVAL_LOST = -2, &
       ARTN_ERR_NUMSTEP     = -3, &
       ARTN_ERR_LARGE_ENER  = -4, &
       ARTN_ERR_OTHER       = -6

  !! filename which is used to pass serialized data
  character(*), parameter :: filename_serial = ".artn_tmpdata"

  !! signal to print on top of data dump file, used in serialize mode
  character(*), parameter :: DATADUMP_FILE_SIGNAL = "datadump_file"

  !> @brief the type t_artn_data contains copies of all data that can be exchanged with pARTn,
  !! coming from another application which calls pARTn as library (ineractive, through API).
  type :: t_artn_data

     !! ============================
     !! data for holding artn input parameters communicated from interactive mode:
     !! they can be set through the routine artn_set() from artn_api.f90.
     !! This data overwrite the working pArtn parameters -- which are located in the
     !! module artn_params -- in the routine refresh_artn()

     integer :: &
          ninit, &
          nevalf_max, &
          lanczos_max_size, &
          lanczos_min_size, &
          neigen, &
          nperp, &
          nsmooth, &
          verbose, &
          zseed, &
          nnewchance, &
          nrelax_print, &
          restart_freq

     real(DP) :: &
          push_dist_thr, &
          forc_thr, &
          eigval_thr, &
          frelax_ene_thr, &
          delr_thr, &
          lanczos_eval_conv_thr, &
          etot_diff_limit, &
          push_step_size, &
          push_step_size_per_atom, &
          lanczos_disp, &
          eigen_step_size, &
          current_step_size, &
          push_over

     !! logicals are stored as integers with 3 possible values:
     !! value 1 represents .true.
     !! value 0 represents .false.
     !! value -1 represents undefined variable
     !! logical :: &
     integer :: &
          lrestart, &
          lrelax, &
          lpush_final, &
          lmove_nextmin, &
          lnperp_limitation, &
          lanczos_at_min, &
          lanczos_always_random


     integer, allocatable :: &
          nperp_limitation(:), &
          push_ids(:)

     real(DP), allocatable :: &
          push_add_const(:,:), &
          push_init(:,:), &
          eigenvec_init(:,:)
     !! need also: eigenvec_init


     character(:), allocatable :: &
          push_mode, &
          engine_units, &
          struc_format_out, &
          push_guess, &
          eigenvec_guess, &
          filout, &
          filin, &
          initpfname, &
          eigenfname, &
          restartfname, &
          converge_property, &
          prefix_min, &
          prefix_sad


     !! ============================
     !! data generated by artn:
     !! these values get written in the routine artn_save_data( step ),
     !! depending on the value of step. The routine is called in several
     !! positions of the main artn() routine.
     !! This data can be extracted after the pArtn run via the function
     !! artn_extract() in artn_api.f90.

     ! integer ::
     ! real(DP) ::
     ! real(DP), allocatable ::
     ! integer, allocatable ::
     ! logical ::
     ! character(:), allocatable ::

     logical :: &
          has_error, &
          has_sad, &
          has_min1, &
          has_min2

     integer :: &
          error_code, &
          nevalf, &
          nevalf_sad, &
          nevalf_min1, &
          nevalf_min2, &
          inewchance, &
          nat

     real(DP) :: &
          energy_init, &
          energy_latest, &
          energy_min1, &
          energy_min2, &
          energy_sad, &
          delr_init, &
          delr_latest, &
          delr_min1, &
          delr_min2, &
          delr_sad, &
          eigval_min1, &
          eigval_min2, &
          eigval_sad, &
          eigval_latest

     integer, allocatable :: &
          typ_latest(:), &
          typ_init(:), &
          typ_min1(:), &
          typ_min2(:), &
          typ_sad(:)

     real(DP), dimension(3,3) :: &
          lat

     real(DP), allocatable :: &
          coords_latest(:,:), &
          coords_init(:,:), &
          coords_min1(:,:), &
          coords_min2(:,:), &
          coords_sad(:,:), &
          eigvec_sad(:,:), &
          eigvec_latest(:,:)

     character(:), allocatable :: &
          error_message

   contains
     procedure :: get_datatype => t_artn_get_datatype
     procedure :: get_datarank => t_artn_get_datarank
     procedure :: get_datasize => t_artn_get_datasize
     procedure :: get_data     => t_artn_get_dataval
     procedure :: dump_input   => t_artn_dump_input
     procedure :: list_set     => t_artn_list_set
     procedure :: list_extract => t_artn_list_extract
     procedure, private :: &
          set_data_int, set_data_real, set_data_logical, set_data_string, &
          set_data_int1d, set_data_real2d
          ! set_data_int2d, set_data_real1d
     generic :: set_data       => &
          set_data_int, set_data_real, set_data_logical, set_data_string, &
          set_data_int1d, set_data_real2d
          ! set_data_int2d, set_data_real1d,
     procedure :: reset_generated => t_artn_data_reset_generated
     ! procedure :: reset_init => t_artn_data_reset_init
     procedure :: read_generated => t_artn_data_read_generated
     procedure :: dump_generated => t_artn_data_dump_generated
     procedure :: serialize_input => t_artn_data_serialize_input
     final :: t_artn_data_destroy
  end type t_artn_data

  interface t_artn_data
     procedure t_artn_data_constructor
  end interface t_artn_data

contains

  !> @brief allocate new ``t_artn_data`` pointer.
  !! The name is overloaded by type name. The values are initialised
  !! such that they indicate "undetermined" values.
  !!
  !! call as:
  !!
  !! ```fortran
  !!    type( t_artn_data ), pointer :: artn_data_ptr
  !!
  !!    artn_data_ptr => t_artn_data()
  !! ```
  function t_artn_data_constructor()result(this)
    implicit none
    type( t_artn_data ), pointer :: this

    allocate( t_artn_data :: this)

    !! int
    this% ninit = -99
    this% nevalf_max = -99
    this% lanczos_max_size = -99
    this% lanczos_min_size = -99
    this% neigen = -99
    this% nperp = -99
    this% nsmooth = -99
    this% verbose = -99
    this% zseed = -99
    this% nnewchance = -99
    this% nrelax_print = -99
    this% restart_freq = -99

    !! real
    this% forc_thr                = 1e20
    this% push_dist_thr           = 1e20
    this% eigval_thr              = 1e20
    this% frelax_ene_thr          = 1e20
    this% delr_thr                = 1e20
    this% lanczos_eval_conv_thr   = 1e20
    this% etot_diff_limit         = 1e20
    this% push_step_size          = 1e20
    this% push_step_size_per_atom = 1e20
    this% lanczos_disp            = 1e20
    this% eigen_step_size         = 1e20
    this% current_step_size       = 1e20
    this% push_over               = 1e20


    !! integer representing logicals, initialize as undefined:
    this% lanczos_at_min        = -1
    this% lrestart              = -1
    this% lrelax                = -1
    this% lpush_final           = -1
    this% lmove_nextmin         = -1
    this% lnperp_limitation     = -1
    this% lanczos_always_random = -1

    !! output
    call this% reset_generated()

  end function t_artn_data_constructor

  !> @brief call reset_generated
  subroutine t_artn_data_destroy( self )
    !! destroy memory of t_artn_data instance
    implicit none
    type( t_artn_data ), intent(inout) :: self
    call self% reset_generated()
  end subroutine t_artn_data_destroy

  !> @brief reset or deallocate all data that can get generated and is held in ``t_artn_data``
  !! Set scalar values to initial.
  subroutine t_artn_data_reset_generated( self )
    !! reset or deallocate all data that can get generated
    implicit none
    class( t_artn_data ), intent(inout) :: self

    self% error_code = 0
    self% has_error = .false.
    self% has_min1 = .false.
    self% has_min2 = .false.
    self% has_sad = .false.
    self% eigval_min1 = 1e20
    self% eigval_min2 = 1e20
    self% eigval_sad = 1e20
    self% eigval_latest = 1e20

    self% nevalf = 0
    self% nevalf_sad = 0
    self% nevalf_min1 = 0
    self% nevalf_min2 = 0

    if( allocated( self% typ_latest   )) deallocate( self% typ_latest )
    if( allocated( self% coords_latest)) deallocate( self% coords_latest )
    if( allocated( self% eigvec_latest )) deallocate( self% eigvec_latest )

    if( allocated( self% typ_init     )) deallocate( self% typ_init )
    if( allocated( self% coords_init  )) deallocate( self% coords_init )

    if( allocated( self% typ_min1     )) deallocate( self% typ_min1 )
    if( allocated( self% coords_min1  )) deallocate( self% coords_min1 )

    if( allocated( self% typ_min2     )) deallocate( self% typ_min2 )
    if( allocated( self% coords_min2  )) deallocate( self% coords_min2 )

    if( allocated( self% typ_sad      )) deallocate( self% typ_sad )
    if( allocated( self% coords_sad   )) deallocate( self% coords_sad )
    if( allocated( self% eigvec_sad   )) deallocate( self% eigvec_sad )
  end subroutine t_artn_data_reset_generated

  ! subroutine t_artn_data_reset_init( self )
  !   !! reset or deallocate all data that is related to initial step of research
  !   implicit none
  !   class( t_artn_data ), intent(inout) :: self

  ! end subroutine t_artn_data_reset_init

  !> @brief get data type encoder.
  !!
  !! return the datatype encoder value for this variable name,
  !! regardless of status of that variable in t_artn_data instance.
  function t_artn_get_datatype( self, name )result( dtype )
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: name
    integer :: dtype
    nop(self)
    select case( name )
    case( &
         "ninit", &
         "nevalf_max", &
         "lanczos_max_size", &
         "lanczos_min_size", &
         "neigen", &
         "nperp", &
         "nsmooth", &
         "verbose", &
         "zseed", &
         "nnewchance", &
         "nrelax_print", &
         "restart_freq", &

         "nperp_limitation", &
         "push_ids", &

         "error_code", "nevalf", "nat", "inewchance", &
         "nevalf_sad", "nevalf_min1", "nevalf_min2", &
         "typ_init", "typ_latest", "typ_min1", "typ_min2", "typ_sad" &

         ); dtype = ARTN_DTYPE_INT
    case( &
         "push_dist_thr", &
         "forc_thr", &
         "eigval_thr", &
         "frelax_ene_thr", &
         "delr_thr", &
         "lanczos_eval_conv_thr", &
         "etot_diff_limit", &
         "push_step_size", &
         "push_step_size_per_atom", &
         "lanczos_disp", &
         "eigen_step_size", &
         "current_step_size", &
         "push_over", &
         "lat", &
         "push_add_const", &
         "push_init", &
         "eigenvec_init", &
         "energy_init", "energy_latest", "energy_min1", "energy_min2", "energy_sad", &
         "delr_init", "delr_latest", "delr_min1", "delr_min2", "delr_sad", &
         "eigval_min1", "eigval_min2", "eigval_sad", "eigval_latest", &
         "coords_init", "coords_latest", "coords_min1", "coords_min2", "coords_sad" ,&
         "eigvec_latest", "eigvec_sad" &
         ); dtype = ARTN_DTYPE_REAL
    case( &
         "lrestart", &
         "lrelax", &
         "lpush_final", &
         "lmove_nextmin", &
         "lnperp_limitation", &
         "lanczos_at_min", &
         "lanczos_always_random", &
         "has_error", "has_sad", "has_min1", "has_min2" &
       ); dtype = ARTN_DTYPE_BOOL
    case( &
         "push_mode", &
         "engine_units", &
         "struc_format_out", &
         "push_guess", &
         "eigenvec_guess", &
         "filout", &
         "filin", &
         "initpfname", &
         "eigenfname", &
         "restartfname", &
         "converge_property", &
         "prefix_min", &
         "prefix_sad", &
         "error_message" &
         ); dtype = ARTN_DTYPE_STR
    case default
       !! unknown name
       dtype = ARTN_DTYPE_UNKNOWN
    end select
  end function t_artn_get_datatype

  !> @brief get data rank
  !!
  !! return the expected datarank for this variable name,
  !! regardless of status in memory (allocated or not)
  function t_artn_get_datarank( self, name )result( drank )
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: name
    integer :: drank
    nop(self)
    select case( name )
    case( &
                                !! int
         "ninit", &
         "nevalf_max", &
         "lanczos_max_size", &
         "lanczos_min_size", &
         "neigen", &
         "nperp", &
         "nsmooth", &
         "verbose", &
         "zseed", &
         "nnewchance", &
         "nrelax_print", &
         "restart_freq", &
                                !! real
         "push_dist_thr", &
         "forc_thr", &
         "eigval_thr", &
         "frelax_ene_thr", &
         "delr_thr", &
         "lanczos_eval_conv_thr", &
         "etot_diff_limit", &
         "push_step_size", &
         "push_step_size_per_atom", &
         "lanczos_disp", &
         "eigen_step_size", &
         "current_step_size", &
         "push_over", &
                                !! logical
         "lrestart", &
         "lrelax", &
         "lpush_final", &
         "lmove_nextmin", &
         "lnperp_limitation", &
         "lanczos_at_min", &
         "lanczos_always_random", &
                                !! str
         "push_mode", &
         "engine_units", &
         "struc_format_out", &
         "push_guess", &
         "eigenvec_guess", &
         "filout", &
         "filin", &
         "initpfname", &
         "eigenfname", &
         "restartfname", &
         "converge_property", &
         "prefix_min", &
         "prefix_sad", &

                                !! generated
         "error_message", &
         "error_code", &
         "nevalf", "nevalf_sad", "nevalf_min1", "nevalf_min2", &
         "nat", &
         "inewchance", &
         "energy_init", "energy_latest", "energy_min1", "energy_min2", "energy_sad", &
         "delr_init", "delr_latest", "delr_min1", "delr_min2", "delr_sad", &
         "eigval_min1", "eigval_min2", "eigval_sad", "eigval_latest", &
         "has_error", "has_sad", "has_min1", "has_min2" &
         ); drank = 0

    case( &
         !! int 1D
         "nperp_limitation", &
         "push_ids", &

         !! generated
         "typ_latest", "typ_init", "typ_min1", "typ_min2", "typ_sad" &
         ); drank = 1

    case( &
                                !! real 2D
         "lat", &
         "push_add_const", &
         "push_init", &
         "eigenvec_init", &
         "coords_init", "coords_latest", "coords_min1", "coords_min2", "coords_sad", &
         "eigvec_latest", "eigvec_sad" &
         ); drank = 2

    case default
       !! unknown name
       drank = -1
    end select
  end function t_artn_get_datarank

  !> @brief get data size
  !!
  !! return c_ptr to array containing number of elements along
  !! each rank (dimension) of data which is present in memory.
  !!
  !! If data is not set in t_artn_data, return negative ierr.
  !! The size of allocatable variables is given by local function size_*_local() because
  !! the intrinsic 'size()' can return random values for unallocated variable.
  function t_artn_get_datasize( self, name, dsize )result( ierr )
    use iso_c_binding, only: c_ptr, c_null_ptr, c_loc
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: name
    integer, allocatable, intent(out) :: dsize(:)
    integer :: ierr
    integer :: drank

    ierr = -1
    drank = self% get_datarank(name)

    !! error in rank (happens when variable name is unknown)
    if( drank < 0 ) return

    allocate( dsize(1:drank), source=0 )
    ierr = 0

    !! rank 0 have no size
    if( drank == 0 ) return

    select case( name )
    case( "nperp_limitation" ); dsize(1) = size_i1d_local( self% nperp_limitation )
    case( "push_ids" ); dsize(1) = size_i1d_local( self% push_ids )
    case( "typ_init" ); dsize(1) = size_i1d_local( self% typ_init )
    case( "typ_latest" ); dsize(1) = size_i1d_local( self% typ_latest )
    case( "typ_min1" ); dsize(1) = size_i1d_local( self% typ_min1 )
    case( "typ_min2" ); dsize(1) = size_i1d_local( self% typ_min2 )
    case( "typ_sad" ); dsize(1) = size_i1d_local( self% typ_sad )

    case( "lat" ); dsize(1) = 3; dsize(2) = 3
    case( "push_add_const" )
       dsize(1) = size_r2d_local( self% push_add_const, 1 )
       dsize(2) = size_r2d_local( self% push_add_const, 2 )
    case( "push_init" )
       dsize(1) = size_r2d_local( self% push_init, 1)
       dsize(2) = size_r2d_local( self% push_init, 2)
    case( "eigenvec_init" )
       dsize(1) = size_r2d_local( self% eigenvec_init, 1)
       dsize(2) = size_r2d_local( self% eigenvec_init, 2)
    case( "coords_init" )
       dsize(1) = size_r2d_local( self% coords_init, 1)
       dsize(2) = size_r2d_local( self% coords_init, 2)
    case( "coords_latest" )
       dsize(1) = size_r2d_local( self% coords_latest, 1)
       dsize(2) = size_r2d_local( self% coords_latest, 2)
    case( "coords_min1" )
       dsize(1) = size_r2d_local( self% coords_min1, 1)
       dsize(2) = size_r2d_local( self% coords_min1, 2)
    case( "coords_min2" )
       dsize(1) = size_r2d_local( self% coords_min2, 1)
       dsize(2) = size_r2d_local( self% coords_min2, 2)
    case( "coords_sad" )
       dsize(1) = size_r2d_local( self% coords_sad, 1)
       dsize(2) = size_r2d_local( self% coords_sad, 2)
    case( "eigvec_latest" )
       dsize(1) = size_r2d_local( self% eigvec_latest, 1)
       dsize(2) = size_r2d_local( self% eigvec_latest, 2)
    case( "eigvec_sad" )
       dsize(1) = size_r2d_local( self% eigvec_sad, 1)
       dsize(2) = size_r2d_local( self% eigvec_sad, 2)
    case default
       !! some different error
       ierr = -2
    end select
  end function t_artn_get_datasize

  !> @brief get data value
  !!
  !! return C_ptr to desired data value, in C precision:
  !!   - c_int for integer;
  !!   - c_double for real;
  !!   - c_bool for logical;
  !!   - c_ptr for string.
  !!
  !! If data of variable name does not exist,
  !! or is not allocated, return null pointer.
  !! This function is called by artn_extract() from artn_api.f90
  function t_artn_get_dataval( self, name )result( dval )
    use iso_c_binding
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: name
    type( c_ptr ) :: dval
    integer, pointer :: iptr, i1ptr(:)
    real( c_double ), pointer :: rptr, r2ptr(:,:)
    logical( c_bool ), pointer :: lptr

    dval = c_null_ptr
    select case( name )
       !! input vars, rank-0 INT
    case( "ninit" )
       allocate( iptr, source = int(self% ninit,c_int) ); dval = c_loc( iptr )
    case( "nevalf_max" )
       allocate( iptr, source = int(self% nevalf_max,c_int) ); dval = c_loc( iptr )
    case( "lanczos_max_size" )
       allocate( iptr, source = int(self% lanczos_max_size,c_int) ); dval = c_loc( iptr )
    case( "lanczos_min_size" )
       allocate( iptr, source = int(self% lanczos_min_size,c_int) ); dval = c_loc( iptr )
    case( "neigen" )
       allocate( iptr, source = int(self% neigen,c_int) ); dval = c_loc( iptr )
    case( "nperp" )
       allocate( iptr, source = int(self% nperp,c_int) ); dval = c_loc( iptr )
    case( "nsmooth" )
       allocate( iptr, source = int(self% nsmooth,c_int) ); dval = c_loc( iptr )
    case( "verbose" )
       allocate( iptr, source = int(self% verbose,c_int) ); dval = c_loc( iptr )
    case( "zseed" )
       allocate( iptr, source = int(self% zseed,c_int) ); dval = c_loc( iptr )
    case( "nnewchance" )
       allocate( iptr, source = int(self% nnewchance,c_int) ); dval = c_loc( iptr )
    case( "nrelax_print" )
       allocate( iptr, source = int(self% nrelax_print,c_int) ); dval = c_loc( iptr )

       !! rank-0 REAL

       !! rank-1 INT
    case( 'nperp_limitation' )
       if( .not. allocated( self% nperp_limitation) ) return
       allocate( i1ptr, source = int(self% nperp_limitation,c_int) ); dval = c_loc( i1ptr(1) )

       !! generated data
    case( "error_message" )
       if( .not. self% has_error ) return
       dval = f2c_string( self% error_message )
    case( "has_error" )
       allocate( lptr, source = logical(self% has_error, c_bool) ); dval = c_loc( lptr )
    case( "has_sad" )
       allocate( lptr, source = logical(self% has_sad, c_bool) ); dval = c_loc( lptr )
    case( "has_min1" )
       allocate( lptr, source = logical(self% has_min1, c_bool) ); dval = c_loc( lptr )
    case( "has_min2" )
       allocate( lptr, source = logical(self% has_min2, c_bool) ); dval = c_loc( lptr )

    case( "error_code" )
       allocate( iptr, source = int(self% error_code, c_int) ); dval = c_loc( iptr )
    case( "nevalf" )
       allocate( iptr, source = int(self% nevalf, c_int) ); dval = c_loc( iptr )
    case( "nevalf_sad" )
       allocate( iptr, source = int(self% nevalf_sad, c_int) ); dval = c_loc( iptr )
    case( "nevalf_min1" )
       allocate( iptr, source = int(self% nevalf_min1, c_int) ); dval = c_loc( iptr )
    case( "nevalf_min2" )
       allocate( iptr, source = int(self% nevalf_min2, c_int) ); dval = c_loc( iptr )
    case( "nat" )
       allocate( iptr, source = int(self% nat, c_int) ); dval = c_loc( iptr )
    case( "inewchance" )
       allocate( iptr, source = int(self% inewchance, c_int) ); dval = c_loc( iptr )

    case( "energy_init" )
       allocate( rptr, source = real( self% energy_init, c_double )); dval = c_loc(rptr)
    case( "energy_latest" )
       if( .not. self% has_error ) return
       allocate( rptr, source = real( self% energy_latest, c_double )); dval = c_loc(rptr)
    case( "energy_min1" )
       if( .not. self% has_min1 ) return
       allocate( rptr, source = real( self% energy_min1, c_double )); dval = c_loc(rptr)
    case( "energy_min2" )
       if( .not. self% has_min2 ) return
       allocate( rptr, source = real( self% energy_min2, c_double )); dval = c_loc(rptr)
    case( "energy_sad" )
       if( .not. self% has_sad ) return
       allocate( rptr, source = real( self% energy_sad, c_double )); dval = c_loc(rptr)

    case( "delr_init" )
       allocate( rptr, source = real( self% delr_init, c_double )); dval = c_loc(rptr)
    case( "delr_latest" )
       if( .not. self% has_error ) return
       allocate( rptr, source = real( self% delr_latest, c_double )); dval = c_loc(rptr)
    case( "delr_min1" )
       if( .not. self% has_min1 ) return
       allocate( rptr, source = real( self% delr_min1, c_double )); dval = c_loc(rptr)
    case( "delr_min2" )
       if( .not. self% has_min2 ) return
       allocate( rptr, source = real( self% delr_min2, c_double )); dval = c_loc(rptr)
    case( "delr_sad" )
       if( .not. self% has_sad ) return
       allocate( rptr, source = real( self% delr_sad, c_double )); dval = c_loc(rptr)

    case( "eigval_latest" )
       if( .not. self% has_error ) return
       allocate( rptr, source = real( self% eigval_latest, c_double )); dval = c_loc(rptr)
    case( "eigval_min1" )
       if( .not. self% has_min1 ) return
       allocate( rptr, source = real( self% eigval_min1, c_double )); dval = c_loc(rptr)
    case( "eigval_min2" )
       if( .not. self% has_min2 ) return
       allocate( rptr, source = real( self% eigval_min2, c_double )); dval = c_loc(rptr)
    case( "eigval_sad" )
       if( .not. self% has_sad ) return
       allocate( rptr, source = real( self% eigval_sad, c_double )); dval = c_loc(rptr)

    case( "typ_latest" )
       if( .not. allocated( self% typ_latest) ) return
       allocate( i1ptr, source = int(self% typ_latest,c_int)); dval = c_loc( i1ptr(1) )
    case( "typ_init" )
       if( .not. allocated( self% typ_init) ) return
       allocate( i1ptr, source = int(self% typ_init,c_int)); dval = c_loc( i1ptr(1) )
    case( "typ_min1" )
       if( .not. allocated( self% typ_min1) ) return
       allocate( i1ptr, source = int(self% typ_min1,c_int)); dval = c_loc( i1ptr(1) )
    case( "typ_min2" )
       if( .not. allocated( self% typ_min2) ) return
       allocate( i1ptr, source = int(self% typ_min2,c_int)); dval = c_loc( i1ptr(1) )
    case( "typ_sad" )
       if( .not. allocated( self% typ_sad) ) return
       allocate( i1ptr, source = int(self% typ_sad,c_int)); dval = c_loc( i1ptr(1) )

    case( "lat" )
       allocate( r2ptr, source = real( self% lat, c_double )); dval = c_loc( r2ptr(1,1) )

    case( "coords_init" )
       if( .not. allocated(self% coords_init) ) return
       allocate( r2ptr, source = real(self% coords_init, c_double) ); dval = c_loc( r2ptr(1,1) )
    case( "coords_latest" )
       if( .not. allocated(self% coords_latest) ) return
       allocate( r2ptr, source = real(self% coords_latest, c_double) ); dval = c_loc( r2ptr(1,1) )
    case( "coords_min1" )
       if( .not. allocated(self% coords_min1) ) return
       allocate( r2ptr, source = real(self% coords_min1, c_double) ); dval = c_loc( r2ptr(1,1) )
    case( "coords_min2" )
       if( .not. allocated(self% coords_min2) ) return
       allocate( r2ptr, source = real(self% coords_min2, c_double) ); dval = c_loc( r2ptr(1,1) )
    case( "coords_sad" )
       if( .not. allocated(self% coords_sad) ) return
       allocate( r2ptr, source = real(self% coords_sad, c_double) ); dval = c_loc( r2ptr(1,1) )

    case( "eigvec_latest" )
       if( .not. allocated( self% eigvec_latest ) ) return
       allocate( r2ptr, source = real(self% eigvec_latest, c_double) ); dval = c_loc( r2ptr(1,1) )
    case( "eigvec_sad" )
       if( .not. allocated( self% eigvec_sad ) ) return
       allocate( r2ptr, source = real(self% eigvec_sad, c_double) ); dval = c_loc( r2ptr(1,1) )
    end select

  end function t_artn_get_dataval


  !! functions for setting the data from interactive mode.. each kind needs a function.
  !! The name is overwritten by generic set_data, which is called from artn_set() in artn_api.f90
  function set_data_int( self, name, val )result( ierr )
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: name
    integer, intent(in) :: val
    integer :: ierr
    ierr = 0
    select case( name )
    case( "ninit"            ); self% ninit = int( val )
    case( "nevalf_max"       ); self% nevalf_max = int( val )
    case( "lanczos_max_size" ); self% lanczos_max_size = int( val )
    case( "lanczos_min_size" ); self% lanczos_min_size = int( val )
    case( "neigen"           ); self% neigen = int( val )
    case( "nperp"            ); self% nperp = int( val )
    case( "nsmooth"          ); self% nsmooth = int( val )
    case( "verbose"          ); self% verbose = int( val )
    case( "zseed"            ); self% zseed = int( val )
    case( "nnewchance"       ); self% nnewchance = int( val )
    case( "nrelax_print"     ); self% nrelax_print = int( val )
    case( "restart_freq"     ); self% restart_freq = int( val )
    case default;            ierr = -1
    end select
  end function set_data_int
  function set_data_int1d( self, name, dim, val )result( ierr )
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: name
    integer, intent(in) :: dim
    integer, dimension(dim), intent(in) :: val
    integer :: ierr
    ierr = 0
    select case( name )
    case( "nperp_limitation" )
       !! if already exists, overwrite with new
       if( allocated(self% nperp_limitation) ) deallocate( self% nperp_limitation )
       allocate( self% nperp_limitation, source = int(val) )
    case( "push_ids" )
       if( allocated(self% push_ids) )deallocate( self% push_ids )
       allocate( self% push_ids, source = int(val))
    case default; ierr = -1
    end select
  end function set_data_int1d
  ! function set_data_int2d( self, name, dim1, dim2, val )result( ierr )
  !   implicit none
  !   class( t_artn_data ), intent(inout) :: self
  !   character(*), intent(in) :: name
  !   integer, intent(in) :: dim1, dim2
  !   integer, dimension(dim1, dim2), intent(in) :: val
  !   integer :: ierr
  !   ierr = 0
  !   select case( name )
  !   ! case( "some_int2d_var" )
  !   !    !! if already exists, overwrite with new
  !   !    if( size(var, 1) ... )
  !   !    if( allocated(self% var) ) deallocate( self% var )
  !   !    allocate( self% var, source = int(val) )
  !   case default; ierr = -1
  !   end select
  ! end function set_data_int2d
  function set_data_real( self, name, val )result( ierr )
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: name
    real(DP), intent(in) :: val
    integer :: ierr
    ierr = 0
    select case( name )
    case( "forc_thr" ); self% forc_thr = real( val, DP )
    case( "push_dist_thr" ); self% push_dist_thr = real( val, DP )
    case( "eigval_thr" ); self% eigval_thr = real( val, DP )
    case( "frelax_ene_thr" ); self% frelax_ene_thr = real( val, DP )
    case( "delr_thr" ); self% delr_thr = real( val, DP )
    case( "lanczos_eval_conv_thr" ); self% lanczos_eval_conv_thr = real( val, DP )
    case( "etot_diff_limit" ); self% etot_diff_limit = real( val, DP )
    case( "push_step_size" ); self% push_step_size = real( val, DP )
    case( "push_step_size_per_atom" ); self% push_step_size_per_atom = real( val, DP )
    case( "lanczos_disp" ); self% lanczos_disp = real( val, DP )
    case( "eigen_step_size" ); self% eigen_step_size = real( val, DP )
    case( "current_step_size" ); self% current_step_size = real( val, DP )
    case( "push_over" ); self% push_over = real( val, DP )
    case default; ierr = -1
    end select
  end function set_data_real
  ! function set_data_real1d( self, name, dim, val )result( ierr )
  !   implicit none
  !   class( t_artn_data ), intent(inout) :: self
  !   character(*), intent(in) :: name
  !   integer, intent(in) :: dim
  !   real(DP), dimension(dim), intent(in) :: val
  !   integer :: ierr
  !   ierr = 0
  !   select case( name )
  !   ! case( "var" )
  !   !    if( allocated( self% var)) deallocate( self% var )
  !   !    allocate( self% var, source = real(val) )
  !   case default; ierr = -1
  !   end select
  ! end function set_data_real1d
  function set_data_real2d( self, name, dim1, dim2, val )result( ierr )
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: name
    integer, intent(in) :: dim1, dim2
    real(DP), dimension(dim1, dim2), intent(in) :: val
    integer :: ierr
    ierr = 0
    select case( name )
       ! case( "var" )
       !    if( allocated( self% var)) deallocate( self% var )
       !    allocate( self% var, source = real(val) )
    case( "push_add_const" )
       if( allocated( self% push_add_const))deallocate( self% push_add_const )
       allocate( self% push_add_const, source = real(val, DP) )
    case( "push_init" )
       if( allocated( self% push_init))deallocate( self% push_init )
       allocate( self% push_init, source = real( val, DP ))
    case( "eigenvec_init" )
       if( allocated( self% eigenvec_init))deallocate( self% eigenvec_init )
       allocate( self% eigenvec_init, source = real( val, DP ))
    case default; ierr = -1
    end select
  end function set_data_real2d
  function set_data_logical( self, name, val ) result( ierr )
    !! logical input is stored as integers:
    !! val = .false. is stored as integer 0
    !! val = .true. is stored as integer 1
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: name
    logical, intent(in) :: val
    integer :: ierr
    integer :: ival
    ierr = 0
    ival = 0
    if( val ) ival = 1
    select case( name )
    case( "lrestart"              ); self% lrestart = ival
    case( "lrelax"                ); self% lrelax = ival
    case( "lpush_final"           ); self% lpush_final = ival
    case( "lmove_nextmin"         ); self% lmove_nextmin = ival
    case( "lnperp_limitation"     ); self% lnperp_limitation = ival
    case( "lanczos_at_min"        ); self% lanczos_at_min = ival
    case( "lanczos_always_random" ); self% lanczos_always_random = ival
    case default;                 ierr = -1
    end select
  end function set_data_logical
  function set_data_string( self, name, val )result( ierr )
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: name
    character(*), intent(in) :: val
    integer :: ierr
    ierr = 0
    select case( name )
    case( "prefix_sad"         ); call local_set_str( self% prefix_sad        , val )
    case( "push_mode"          ); call local_set_str( self% push_mode         , val )
    case( "engine_units"       ); call local_set_str( self% engine_units      , val )
    case( "struc_format_out"   ); call local_set_str( self% struc_format_out  , val )
    case( "push_guess"         ); call local_set_str( self% push_guess        , val )
    case( "eigenvec_guess"     ); call local_set_str( self% eigenvec_guess    , val )
    case( "filout"             ); call local_set_str( self% filout            , val )
    case( "filin"              ); call local_set_str( self% filin             , val )
    case( "initpfname"         ); call local_set_str( self% initpfname        , val )
    case( "eigenfname"         ); call local_set_str( self% eigenfname        , val )
    case( "restartfname"       ); call local_set_str( self% restartfname      , val )
    case( "converge_property"  ); call local_set_str( self% converge_property , val )
    case( "prefix_min"         ); call local_set_str( self% prefix_min        , val )
    case default; ierr = -1
    end select
  end function set_data_string


  !> @brief dump the contents of self into serialization file
  function t_artn_data_serialize_input( self ) result( ierr )
    implicit none
    class( t_artn_data ), intent(inout) :: self
    integer :: ierr

    ierr = self% dump_input( "serialize" )
    if( ierr .ne. 0 ) then
       write(*,*) repeat("=",80)
       write(*,*) "error in t_artn_data_serialize_input", ierr
       write(*,*) repeat("=",80)
    end if
    !! reset the generated data inside self
    call self% reset_generated()

  end function t_artn_data_serialize_input


  !> @brief dump the defined values of t_artn_data into a file that can be used as artn input.
  function t_artn_dump_input( self, fname ) result( ierr )
    !!
    !! NOTE: using write(*, nml= ...) will output ALL the things in namelist, including undefined. Not good.
    !! NOTE2: Not all data in sumped for the moment, e.g. push_init, push_add_const, etc.
    implicit none
    class( t_artn_data ), intent(inout) :: self
    character(*), intent(in) :: fname
    integer :: ierr

    character(:), allocatable :: f
    integer :: u0, ios
    integer :: dt(8)
    character(*), parameter :: default_filename = "artn_tmpinp.in"

    ierr = 0

    !! rename to some default name
    if( fname == "default_filename" ) then
       allocate( f, source = default_filename )
    elseif( fname == "serialize" ) then
       !! use the serialization file
       allocate( f, source = filename_serial )
    else
       allocate( f, source = fname )
    end if

    !! always overwrite existing file, status="replace"
    open(newunit=u0, file=f, status="replace", iostat=ios )
    if( ios /= 0 ) then
       write(*,*) "PROBLEM WITH OPENING FILE FOR INPUT DUMP:",f
       ierr = -1
       return
    end if

    !! get date and time
    call date_and_time( values = dt )
    !! write the namelist for input manually, since there could be unallocated things ...
    write(u0, *) "!! This input file was written by the function t_artn_data_dump_input(),"
    write(u0, "(1x,a,1x,i0,a1,i0,a1,i0,1x,a,1x,i0.2,a1,i0.2,a1,i0.2//)") "!! launched on:", &
         dt(3),".",dt(2),".",dt(1),"at:",dt(5),":",dt(6),":",dt(7)

    !! begin writing the namelist
    write(u0, *) "&ARTN_PARAMETERS"

    !! check all possible params

    !! if param is defined, print it

    if( self% ninit            .ne. -99 ) write(u0, '(3x,a,1x,i0)') "ninit            =", self% ninit
    if( self% nevalf_max       .ne. -99 ) write(u0, '(3x,a,1x,i0)') "nevalf_max       =", self% nevalf_max
    if( self% lanczos_max_size .ne. -99 ) write(u0, '(3x,a,1x,i0)') "lanczos_max_size =", self% lanczos_max_size
    if( self% lanczos_min_size .ne. -99 ) write(u0, '(3x,a,1x,i0)') "lanczos_min_size =", self% lanczos_min_size
    if( self% neigen           .ne. -99 ) write(u0, '(3x,a,1x,i0)') "neigen           =", self% neigen
    if( self% nperp            .ne. -99 ) write(u0, '(3x,a,1x,i0)') "nperp            =", self% nperp
    if( self% nsmooth          .ne. -99 ) write(u0, '(3x,a,1x,i0)') "nsmooth          =", self% nsmooth
    if( self% verbose          .ne. -99 ) write(u0, '(3x,a,1x,i0)') "verbose          =", self% verbose
    if( self% zseed            .ne. -99 ) write(u0, '(3x,a,1x,i0)') "zseed            =", self% zseed
    if( self% nnewchance       .ne. -99 ) write(u0, '(3x,a,1x,i0)') "nnewchance       =", self% nnewchance
    if( self% nrelax_print     .ne. -99 ) write(u0, '(3x,a,1x,i0)') "nrelax_print     =", self% nrelax_print
    if( self% restart_freq     .ne. -99 ) write(u0, '(3x,a,1x,i0)') "restart_freq     =", self% restart_freq


    if( .not.(self% forc_thr                > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "forc_thr                =", self% forc_thr
    if( .not.(self% push_dist_thr           > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "push_dist_thr           =", self% push_dist_thr
    if( .not.(self% eigval_thr              > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "eigval_thr              =", self% eigval_thr
    if( .not.(self% frelax_ene_thr          > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "frelax_ene_thr          =", self% frelax_ene_thr
    if( .not.(self% delr_thr                > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "delr_thr                =", self% delr_thr
    if( .not.(self% lanczos_eval_conv_thr   > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "lanczos_eval_conv_thr   =", self% lanczos_eval_conv_thr
    if( .not.(self% etot_diff_limit         > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "etot_diff_limit         =", self% etot_diff_limit
    if( .not.(self% push_step_size          > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "push_step_size          =", self% push_step_size
    if( .not.(self% push_step_size_per_atom > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "push_step_size_per_atom =", self% push_step_size_per_atom
    if( .not.(self% lanczos_disp            > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "lanczos_disp            =", self% lanczos_disp
    if( .not.(self% eigen_step_size         > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "eigen_step_size         =", self% eigen_step_size
    if( .not.(self% push_over               > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "push_over               =", self% push_over
    if( .not.(self% current_step_size       > 1e19 ) )&
         write(u0, '(3x,a,1x,g0.6)') "current_step_size       =", self% current_step_size

    if( self% lanczos_at_min        == 0 ) write(u0, "(3x,a)" ) "lanczos_at_min        = .false."
    if( self% lanczos_at_min        == 1 ) write(u0, "(3x,a)" ) "lanczos_at_min        = .true."
    if( self% lrestart              == 0 ) write(u0, "(3x,a)" ) "lrestart              = .false."
    if( self% lrestart              == 1 ) write(u0, "(3x,a)" ) "lrestart              = .true."
    if( self% lrelax                == 0 ) write(u0, "(3x,a)" ) "lrelax                = .false."
    if( self% lrelax                == 1 ) write(u0, "(3x,a)" ) "lrelax                = .true."
    if( self% lpush_final           == 0 ) write(u0, "(3x,a)" ) "lpush_final           = .false."
    if( self% lpush_final           == 1 ) write(u0, "(3x,a)" ) "lpush_final           = .true."
    if( self% lmove_nextmin         == 0 ) write(u0, "(3x,a)" ) "lmove_nextmin         = .false."
    if( self% lmove_nextmin         == 1 ) write(u0, "(3x,a)" ) "lmove_nextmin         = .true."
    if( self% lnperp_limitation     == 0 ) write(u0, "(3x,a)" ) "lnperp_limitation     = .false."
    if( self% lnperp_limitation     == 1 ) write(u0, "(3x,a)" ) "lnperp_limitation     = .true."
    if( self% lanczos_always_random == 0 ) write(u0, "(3x,a)" ) "lanczos_always_random = .false."
    if( self% lanczos_always_random == 1 ) write(u0, "(3x,a)" ) "lanczos_always_random = .true."

    if( allocated( self% prefix_sad       )) &
         write(u0, "(3x,a,a,a)") "prefix_sad        = '", self% prefix_sad,"'"
    if( allocated (self% engine_units     )) &
         write(u0, "(3x,a,a,a)") "engine_units      = '", self% engine_units, "'"
    if( allocated (self% struc_format_out )) &
         write(u0, "(3x,a,a,a)") "struc_format_out  = '", self% struc_format_out, "'"
    if( allocated (self% filout           )) &
         write(u0, "(3x,a,a,a)") "filout            = '", self% filout, "'"
    if( allocated (self% filin            )) &
         write(u0, "(3x,a,a,a)") "filin             = '", self% filin, "'"
    if( allocated (self% initpfname       )) &
         write(u0, "(3x,a,a,a)") "initpfname        = '", self% initpfname, "'"
    if( allocated (self% eigenfname       )) &
         write(u0, "(3x,a,a,a)") "eigenfname        = '", self% eigenfname, "'"
    if( allocated (self% restartfname     )) &
         write(u0, "(3x,a,a,a)") "restartfname      = '", self% restartfname, "'"
    if( allocated (self% converge_property)) &
         write(u0, "(3x,a,a,a)") "converge_property = '", self% converge_property, "'"
    if( allocated (self% prefix_min       )) &
         write(u0, "(3x,a,a,a)") "prefix_min        = '", self% prefix_min, "'"


    if( allocated( self% nperp_limitation) ) then
       write(u0, '(3x,a,*(i0,:,",",1x))') "nperp_limitation = ", self% nperp_limitation
    end if

    if( allocated( self% push_ids ) ) then
       write(u0,'(3x,a,*(i0,:,",",1x))') "push_ids = ", self% push_ids
    end if

    if( allocated( self% push_add_const ) ) then
       write(u0, '(3x,a,*(f0.12,:,",",1x))') "push_add_const=", self% push_add_const
    end if

    if( allocated( self% push_init ) ) then
       self% push_mode = "input"
       write(u0, '(3x,a,*(f0.12,:,","))') "push = ",self% push_init
    end if

    if( allocated( self% eigenvec_init ) ) then
       self% eigenvec_guess = "input"
       write(u0, '(3x,a,*(f0.12,:,","))') "eigenvec =", self% eigenvec_init
    end if

    if( allocated (self% push_mode        )) &
         write(u0, "(3x,a,a,a)") "push_mode         = '", self% push_mode,"'"
    if( allocated (self% eigenvec_guess   )) &
         write(u0, "(3x,a,a,a)") "eigenvec_guess    = '", self% eigenvec_guess, "'"
    if( allocated (self% push_guess       )) &
         write(u0, "(3x,a,a,a)") "push_guess        = '", self% push_guess, "'"

    write(u0, *) "/"

    close(u0, status="keep" )
    deallocate( f )
  end function t_artn_dump_input


  !> @brief dump the generated data into a tmp file
  !!
  !! The tmp file is the same as serialization file, it gets overwritten!
  subroutine t_artn_data_dump_generated( self )
    implicit none
    class( t_artn_data ), intent(inout) :: self

    integer :: u0, ios
    character(len=255) :: msg

    !! always overwrite if existing
    open( newunit=u0, file=filename_serial, access="stream", form="formatted", &
         action="write", status="replace", iostat=ios, iomsg=msg )
    if( ios .ne. 0 ) then
       write(*,*) repeat('=',80)
       write(*,*) ">> error in dump_generated: tmp file for passing data has error!!", ios
       write(*,*) trim(msg)
       return
    end if

    !! output some variables outside of namelist, since
    !! it is not allocatable, and only needs single value.
    !! common
    write(u0, *) DATADUMP_FILE_SIGNAL
    write(u0, *) self% has_error
    write(u0, *) self% error_code
    if( self% has_error ) write(u0, *) self% error_message
    write(u0, *) self% nevalf
    write(u0, *) self% nevalf_sad
    write(u0, *) self% nevalf_min1
    write(u0, *) self% nevalf_min2
    write(u0, *) self% inewchance

    !! struc flags
    write(u0, *) self% has_sad
    write(u0, *) self% has_min1
    write(u0, *) self% has_min2

    !! nat is needed to allocate vectors which will receive data
    !! all struc
    write(u0, *) self% nat
    write(u0, *) self% lat

    !! energies
    write(u0, *) self% energy_init
    write(u0, *) self% energy_sad
    write(u0, *) self% energy_min1
    write(u0, *) self% energy_min2
    write(u0, *) self% energy_latest

    !! delr
    write(u0, *) self% delr_init
    write(u0, *) self% delr_sad
    write(u0, *) self% delr_min1
    write(u0, *) self% delr_min2
    write(u0, *) self% delr_latest

    !! eigval
    write(u0, *) self% eigval_sad
    write(u0, *) self% eigval_min1
    write(u0, *) self% eigval_min2
    write(u0, *) self% eigval_latest

    !! ==== output these as fake nml ====
    !! why: easier to read them, but don't know which are defined a-priori
    !! init
    write(u0, *) "&strucs"
    write(u0, '(a,*(i0,",",:))') "typ_init=",self% typ_init
    write(u0, '(a,*(g0.12,",",:))') "coords_init=",self% coords_init

    !! min1
    if( self% has_min1 ) then
       write(u0, '(a,*(i0,","))') "typ_min1=",self% typ_min1
       write(u0, '(a,*(g0.12,","))') "coords_min1=",self% coords_min1
    endif

    !! min2
    if( self% has_min2 ) then
       write(u0, '(a,*(i0,","))') "typ_min2=",self% typ_min2
       write(u0, '(a,*(g0.12,","))') "coords_min2=",self% coords_min2
    end if


    !! sad
    if( self% has_sad ) then
       write(u0, '(a,*(i0,","))') "typ_sad=", self% typ_sad
       write(u0, '(a,*(g0.12,","))') "coords_sad=", self% coords_sad
       write(u0, '(a,*(g0.12,","))') "eigvec_sad=", self% eigvec_sad
    end if


    !! latest
    if( self% has_error ) then
       write(u0, '(a,*(i0,","))') "typ_latest=",self% typ_latest
       write(u0, '(a,*(g0.12,","))') "coords_latest=",self% coords_latest
       write(u0, '(a,*(g0.12,","))') "eigvec_latest=",self% eigvec_latest
    end if

    write(u0, '(a1)') "/"
    close( u0, status="keep" )

  end subroutine t_artn_data_dump_generated

  !> @brief read the generated data from tmp file
  function t_artn_data_read_generated( self )result(ierr)
    !! The format to read should strictly follow the format in dump_generated!
    !! NOTE: the data file is "consumed" (deleted) after it is read.
    implicit none
    class( t_artn_data ), intent(inout) :: self
    integer :: ierr

    integer :: u0, ios
    character(len=255) :: str
    character(len=5000) :: line
    !! local vars for keeping coherent in names with namelist
    integer, allocatable :: typ_init(:), typ_sad(:), typ_min1(:), typ_min2(:), typ_latest(:)
    real(DP), allocatable :: coords_init(:,:), coords_sad(:,:), coords_min1(:,:), &
         coords_min2(:,:), coords_latest(:,:), eigvec_latest(:,:), eigvec_sad(:,:)

    namelist/strucs/typ_init, typ_sad, typ_min1, typ_min2, typ_latest
    namelist/strucs/coords_init, coords_sad, coords_min1, coords_min2, coords_latest
    namelist/strucs/eigvec_latest, eigvec_sad


    ! write(*,*) "in t_artn_data_read_generated"

    ierr = 0

    !! this file should exist, problem if dont
    open( newunit=u0, file=filename_serial, access = "stream", form = "formatted", &
         action="read", status="old", iostat=ios, iomsg=str)
    if( ios .ne. 0 ) then
       write(*,*) repeat('=', 80)
       write(*,*) ">> error in read_generated: tmp datafile has error:", ios
       write(*,*) trim(str)
       ierr = -1
       return
    end if

    !! read
    read(u0, '(a255)', iostat=ios) str
    if( trim(str) /= DATADUMP_FILE_SIGNAL .or. ios /= 0 ) then
       !! this is not an output dump file, exit
       write(*,*) repeat('=',80)
       write(*,*) ">> file does not look like pARTn data dump:",filename_serial
       ierr = -2
       return
    end if

    read(u0, *) self% has_error
    read(u0, *) self% error_code
    if( self% has_error) then
       read(u0, '(a256)') str
       if( allocated( self% error_message))deallocate( self% error_message)
       allocate( self% error_message, source=trim(str) )
    end if
    read(u0, *) self% nevalf
    read(u0, *) self% nevalf_sad
    read(u0, *) self% nevalf_min1
    read(u0, *) self% nevalf_min2
    read(u0, *) self% inewchance

    !! struc flags
    read(u0, *) self% has_sad
    read(u0, *) self% has_min1
    read(u0, *) self% has_min2

    !! all struc
    read(u0, *) self% nat
    read(u0, *) self% lat

    !! energies
    read(u0, *) self% energy_init
    read(u0, *) self% energy_sad
    read(u0, *) self% energy_min1
    read(u0, *) self% energy_min2
    read(u0, *) self% energy_latest

    !! delr
    read(u0, *) self% delr_init
    read(u0, *) self% delr_sad
    read(u0, *) self% delr_min1
    read(u0, *) self% delr_min2
    read(u0, *) self% delr_latest

    !! eigval
    read(u0, *) self% eigval_sad
    read(u0, *) self% eigval_min1
    read(u0, *) self% eigval_min2
    read(u0, *) self% eigval_latest

    !! allocate vectors to receive data
    allocate( typ_init(1:self% nat))
    allocate( coords_init(1:3,1:self% nat))
    if( self% has_min1 ) then
       allocate( typ_min1(1:self% nat) )
       allocate( coords_min1(1:3,1:self% nat))
    end if
    if( self% has_min2 ) then
       allocate( typ_min2(1:self% nat) )
       allocate( coords_min2(1:3,1:self% nat))
    end if
    if( self% has_sad ) then
       allocate( typ_sad(1:self% nat))
       allocate( coords_sad(1:3,1:self% nat))
       allocate( eigvec_sad(1:3,1:self% nat))
    end if
    if( self% has_error ) then
       allocate( typ_latest(1:self% nat))
       allocate( coords_latest(1:3,1:self% nat))
       allocate( eigvec_latest(1:3,1:self% nat))
    end if

    ! write(*,*) "read has_min1",self% has_min1
    ! write(*,*) "read has_min2",self% has_min2

    !! read strucs as nml
    read(u0, nml=strucs, iostat = ios)
    if( ios .ne. 0 ) then
       backspace(u0)
       read(u0, '(a)') line
       write(*,*) ">> err reading nml=strucs:"
       write(*,*) trim(line)
       ierr = -2
       return
    end if



    !! move alloc to self object, this will deallocate source vecs
    if( self% has_sad ) then
       call move_alloc( coords_sad, self% coords_sad )
       call move_alloc( typ_sad, self% typ_sad )
       call move_alloc( eigvec_sad, self% eigvec_sad )
    end if
    if( self% has_min1 ) then
       call move_alloc( typ_min1, self% typ_min1 )
       call move_alloc( coords_min1, self% coords_min1 )
    end if
    if( self% has_min2 ) then
       call move_alloc( typ_min2, self% typ_min2 )
       call move_alloc( coords_min2, self% coords_min2 )
    end if
    if( self% has_error ) then
       call move_alloc( typ_latest, self% typ_latest )
       call move_alloc( coords_latest, self% coords_latest )
       call move_alloc( eigvec_latest, self% eigvec_latest )
    end if

    !! close and delete the serialized file
    close( u0, status="delete")

  end function t_artn_data_read_generated



  !> \cond
  subroutine t_artn_list_extract( self )
    !! write all variables that can be extracted from t_artn_data
    class( t_artn_data ), intent(inout) :: self

    nop(self)
    write(*,*) "List of variables which can be extracted from t_artn_data:"
    write(*,*) repeat('=',80)
    write(*,'(3x, "name              :",3x,a8,3x,a4,3x,a)') "type", "rank", "size"
    write(*,*) repeat('=',80)

    write(*, '(3x, "Information about the current run:")')
    write(*, '(3x,"has_error         :",3x,a8,3x,a4,3x,a )') "logical", "0","0"
    write(*, '(3x,"error_code        :",3x,a8,3x,a4,3x,a )') "integer","0","0"
    write(*, '(3x,"error_message     :",3x,a8,3x,a4,3x,a )') "string","0","any"
    write(*, '(3x,"nevalf            :",3x,a8,3x,a4,3x,a )') "integer","0","0"
    write(*, '(3x,"inewchance        :",3x,a8,3x,a4,3x,a )') "integer","0","0"
    write(*,*)
    write(*, '(3x,"Initial structure:")')
    write(*, '(3x,"nat               :",3x,a8,3x,a4,3x,a )') "integer","0","0"
    write(*, '(3x,"lat               :",3x,a8,3x,a4,3x,a )') "real", "2","(3,3)"
    write(*, '(3x,"energy_init       :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"delr_init         :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"typ_init          :",3x,a8,3x,a4,3x,a )') "integer","1","natoms"
    write(*, '(3x,"coords_init       :",3x,a8,3x,a4,3x,a )') "real", "2","fortran (3,nat); python [nat,3]"
    write(*,*)
    write(*, '(3x,"Saddle structure:")')
    write(*, '(3x,"has_sad           :",3x,a8,3x,a4,3x,a )') "logical", "0","0"
    write(*, '(3x,"energy_sad        :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"delr_sad          :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"eigval_sad        :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"typ_sad           :",3x,a8,3x,a4,3x,a )') "integer","1","natoms"
    write(*, '(3x,"coords_sad        :",3x,a8,3x,a4,3x,a )') "real", "2","fortran (3,nat); python [nat,3]"
    write(*, '(3x,"eigvec_sad        :",3x,a8,3x,a4,3x,a )') "real", "2","fortran (3,nat); python [nat,3]"
    write(*, '(3x,"nevalf_sad        :",3x,a8,3x,a4,3x,a )') "integer","0","0"
    write(*,*)
    write(*, '(3x,"Minimum1 structure:")')
    write(*, '(3x,"has_min1          :",3x,a8,3x,a4,3x,a )') "logical", "0","0"
    write(*, '(3x,"energy_min1       :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"delr_min1         :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"eigval_min1       :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"typ_min1          :",3x,a8,3x,a4,3x,a )') "integer","1","natoms"
    write(*, '(3x,"coords_min1       :",3x,a8,3x,a4,3x,a )') "real", "2","fortran (3,nat); python [nat,3]"
    write(*, '(3x,"nevalf_min1       :",3x,a8,3x,a4,3x,a )') "integer","0","0"
    write(*,*)
    write(*, '(3x,"Minimum2 structure:")')
    write(*, '(3x,"has_min2          :",3x,a8,3x,a4,3x,a )') "logical", "0","0"
    write(*, '(3x,"energy_min2       :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"delr_min2         :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"eigval_min2       :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"typ_min2          :",3x,a8,3x,a4,3x,a )') "integer","1","natoms"
    write(*, '(3x,"coords_min2       :",3x,a8,3x,a4,3x,a )') "real", "2","fortran (3,nat); python [nat,3]"
    write(*, '(3x,"nevalf_min2       :",3x,a8,3x,a4,3x,a )') "integer","0","0"
    write(*,*)
    write(*, '(3x,"Latest structure (only available in case of error):")')
    write(*, '(3x,"energy_latest     :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"delr_latest       :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"eigval_latest     :",3x,a8,3x,a4,3x,a )') "real","0","0"
    write(*, '(3x,"typ_latest        :",3x,a8,3x,a4,3x,a )') "integer","1","natoms"
    write(*, '(3x,"coords_latest     :",3x,a8,3x,a4,3x,a )') "real", "2","fortran (3,nat); python [nat,3]"
    write(*, '(3x,"eigvec_latest     :",3x,a8,3x,a4,3x,a )') "real", "2","fortran (3,nat); python [nat,3]"
  end subroutine t_artn_list_extract

  subroutine t_artn_list_set( self )
    !! write all variables that can be set into the t_artn_data type
    class( t_artn_data ), intent(inout) :: self

    nop(self)
    write(*,*) "List of variables which can be set into the t_artn_data:"
    write(*,'(3x, "name                   :",3x,a8,3x,a4,3x,a)') "type", "rank", "size"
    write(*,*) repeat('=',80)
    write(*,'(3x, "converge_property      :",3x,a8,3x,a4,3x,a)') "string", "0", "any"
    write(*,'(3x, "current_step_size      :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "delr_thr               :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "eigenfname             :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 255"
    write(*,'(3x, "eigen_step_size        :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "eigenvec_guess         :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 255"
    write(*,'(3x, "eigenvec_init          :",3x,a8,3x,a4,3x,a)') "real", "2", "fortran (3,nat); python [nat,3]"
    write(*,'(3x, "eigval_thr             :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "engine_units           :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 256"
    write(*,'(3x, "etot_diff_limit        :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "filout                 :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 255"
    write(*,'(3x, "filin                  :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 255"
    write(*,'(3x, "forc_thr               :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "frelax_ene_thr         :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "initpfname             :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 255"
    write(*,'(3x, "lanczos_always_random  :",3x,a8,3x,a4,3x,a)') "logical", "0", "0"
    write(*,'(3x, "lanczos_at_min         :",3x,a8,3x,a4,3x,a)') "logical", "0", "0"
    write(*,'(3x, "lanczos_disp           :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "lanczos_eval_conv_thr  :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "lanczos_max_size       :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "lanczos_min_size       :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "lmove_nextmin          :",3x,a8,3x,a4,3x,a)') "logical", "0", "0"
    write(*,'(3x, "lnperp_limitation      :",3x,a8,3x,a4,3x,a)') "logical", "0", "0"
    write(*,'(3x, "lpush_final            :",3x,a8,3x,a4,3x,a)') "logical", "0", "0"
    write(*,'(3x, "lrelax                 :",3x,a8,3x,a4,3x,a)') "logical", "0", "0"
    write(*,'(3x, "lrestart               :",3x,a8,3x,a4,3x,a)') "logical", "0", "0"
    write(*,'(3x, "nevalf_max             :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "neigen                 :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "ninit                  :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "nnewchance             :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "nperp                  :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "nperp_limitation       :",3x,a8,3x,a4,3x,a)') "integer", "1", "any"
    write(*,'(3x, "nrelax_print           :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "nsmooth                :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "push_add_const         :",3x,a8,3x,a4,3x,a)') "real", "2", "fortran (4,nat); python [nat,4]"
    write(*,'(3x, "push_dist_thr          :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "push_guess             :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 255"
    write(*,'(3x, "push_ids               :",3x,a8,3x,a4,3x,a)') "integer", "1", ".le. natoms"
    write(*,'(3x, "push_init              :",3x,a8,3x,a4,3x,a)') "real", "2", "fortran (3,nat); python [nat,3]"
    write(*,'(3x, "push_mode              :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 5"
    write(*,'(3x, "push_over              :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "push_step_size         :",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "push_step_size_per_atom:",3x,a8,3x,a4,3x,a)') "real", "0","0"
    write(*,'(3x, "prefix_sad             :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 255"
    write(*,'(3x, "prefix_min             :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 255"
    write(*,'(3x, "restart_freq           :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "restartfname           :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 255"
    write(*,'(3x, "struc_format_out       :",3x,a8,3x,a4,3x,a)') "string", "0", ".le. 10"
    write(*,'(3x, "verbose                :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"
    write(*,'(3x, "zseed                  :",3x,a8,3x,a4,3x,a)') "integer", "0", "0"

  end subroutine t_artn_list_set


  !! local functions
  !! calling size for unallocated stuff can give undefined (random) result, so wrap them
  !! to return size=0 for unallocated
  function lenstr_local( str )result(l)
    character(:), allocatable, intent(in) :: str
    integer :: l
    l = 0
    if( .not. allocated(str)) return
    l = len_trim( str )
  end function lenstr_local
  function size_i1d_local( i1d )result(l)
    integer, allocatable, intent(in) :: i1d(:)
    integer :: l
    l = 0
    if( .not. allocated(i1d)) return
    l = size( i1d )
  end function size_i1d_local
  function size_i2d_local( i2d, ax )result(l)
    integer, allocatable, intent(in) :: i2d(:,:)
    integer, intent(in) :: ax
    integer :: l
    l = 0
    if( .not. allocated(i2d)) return
    l = size( i2d, ax )
  end function size_i2d_local
  function size_r1d_local( r1d )result(l)
    real(DP), allocatable, intent(in) :: r1d(:)
    integer :: l
    l = 0
    if( .not. allocated(r1d)) return
    l = size( r1d )
  end function size_r1d_local
  function size_r2d_local( r2d, ax )result(l)
    real(DP), allocatable, intent(in) :: r2d(:,:)
    integer, intent(in) :: ax
    integer :: l
    l = 0
    if( .not. allocated(r2d)) return
    l = size( r2d, ax )
  end function size_r2d_local

  subroutine local_set_str( str, val )
    character(:), allocatable, intent(inout) :: str
    character(*), intent(in) :: val
    if( allocated( str ) ) deallocate( str )
    allocate( str, source = val )
  end subroutine local_set_str


  function f2c_string( str ) result(ptr)
    use iso_c_binding, only: c_char, c_null_char, c_ptr, c_loc
    implicit none
    character(*), intent(in) :: str
    type( c_ptr ) :: ptr
    character(len=1, kind=c_char), pointer :: sptr(:)
    integer :: i, n
    n = len( str )
    allocate(sptr(1:n+1) )
    do i = 1, n
       sptr(i) = str(i:i)
    end do
    sptr(n+1) = c_null_char
    ptr = c_loc(sptr)
  end function f2c_string
  !! \endcond


end module artn_data
